Migrate from `leavesmc.top` to `leavesmc.org`
LeavesMC/Leaves pull request #197
Opened 2024-03-25 23:47 UTC by Bluemangoo

fix #195 

`repo.leavesmc.[top|org]`  没改因为后面 ssl 证书还是 .top 的。

2024-03-28 17:23 UTC, s-yh-china requested changes

2024-03-28 17:23 UTC, s-yh-china commented on patches/server/0103-Leaves-update-command.patch
> -+            HttpURLConnection connection = (HttpURLConnection) new URL("https://api.leavesmc.top/projects/leaves/versions/" + mcVersion + "/builds/latest").openConnection();
这里可能有些问题，v2和v1的部分逻辑是不一样的，需要更多调整

2024-03-28 17:23 UTC, s-yh-china commented on patches/server/0103-Leaves-update-command.patch
> -+            HttpURLConnection connection = (HttpURLConnection) new URL("https://api.leavesmc.top/projects/leaves/versions/" + mcVersion + "/builds/latest").openConnection();
并且实际上v1已经恢复了，我们没有修改的必要

2024-03-28 23:35 UTC, Bluemangoo commented on patches/server/0103-Leaves-update-command.patch
> -+            HttpURLConnection connection = (HttpURLConnection) new URL("https://api.leavesmc.top/projects/leaves/versions/" + mcVersion + "/builds/latest").openConnection();
v1和v2哪些地方有区别。我记得是全兼容的。

2024-03-28 23:38 UTC, Bluemangoo commented
表现好像要用的部分都没有什么区别。

![image](https://github.com/LeavesMC/Leaves/assets/63218454/079c7c4e-f0b2-4521-ada6-254d220b2cd8)

2024-03-28 23:43 UTC, Bluemangoo commented
top.leavesmc.leaves.util.LeavesVersionFetcher:54-59

？ 

```java
versionInfo = versionInfo.replace("\"", "");
        try {
            distance = fetchDistanceFromLeavesApiV2(getMinecraftVersion(), versionInfo);
        } catch (NumberFormatException ignored) {
            distance = fetchDistanceFromGitHub(repo, branch, versionInfo);
        }
```

2024-03-29 04:14 UTC, Bluemangoo commented
我到时候做个try v1 失败换 v2 好了。

2024-03-29 06:39 UTC, Bluemangoo commented
我简单粗暴一下好了。

```java
            if (connection.getResponseCode() % 100 != 2){
                connection = (HttpURLConnection) new URL("https://api.leavesmc.org/v2/projects/leaves/versions/" + mcVersion + "/builds/latest").openConnection();
                connection.connect();
            };
```

2024-03-29 06:46 UTC, Bluemangoo commented
等 api 那边做好再合并吧。

2024-03-29 08:08 UTC, MC-XiaoHei commented
apiv2并不会采用和v1同样的下载逻辑，或者说从一开始就必须使用下载api进行下载。
至于cdn，让姐姐部署proxy吧（
参考[API Docs](https://api.leavesmc.top/v2/docs)

2024-03-29 08:55 UTC, Bluemangoo commented
下载api是哪个，给个example。

我看看z0的cdn是怎么样的。

2024-03-29 09:10 UTC, MC-XiaoHei commented
> 下载api给个example。
> 
> 我看看z0的cdn是怎么样的。

![Screenshot_20240329_170933_com.microsoft.emmx.canary.jpg](https://github.com/LeavesMC/Leaves/assets/100807593/38394c36-3402-46e9-92cb-2ea7b7078b78)
就是个重定向

2024-03-29 09:10 UTC, MC-XiaoHei commented
> > 下载api给个example。
> > 
> > 我看看z0的cdn是怎么样的。
> 
> ![Screenshot_20240329_170933_com.microsoft.emmx.canary.jpg](https://github.com/LeavesMC/Leaves/assets/100807593/38394c36-3402-46e9-92cb-2ea7b7078b78)
> 就是个重定向

哦不 描述错了

2024-03-29 09:56 UTC, MC-XiaoHei commented
要不等1205更新彻底换v2+org域名吧
别老判断了（
到时候proxy也部署了应该

2024-03-29 09:59 UTC, s-yh-china commented
在中国境内的下载cloudflare不可能比得过国内厂商的cdn的

2024-03-29 10:01 UTC, MC-XiaoHei commented
> 在中国境内的下载cloudflare不可能比得过国内厂商的cdn的

这个确实，但是现在自动更新也没走cdn啊（
以及vercel速度也还行

2024-03-29 12:23 UTC, Bluemangoo commented
姐姐快部署proxy。cf的速度还可以的。

v2这边是用z0的cdn还是等proxy？

2024-03-29 12:24 UTC, Bluemangoo commented
HttpUrlConnection 默认 follow redirect 吗。

2024-03-29 12:26 UTC, MC-XiaoHei commented
> 姐姐快部署proxy。cf的速度还可以的。
> 
> v2这边是用z0的cdn还是等proxy？

z0允许就加上吧

2024-03-29 12:27 UTC, MC-XiaoHei commented
> HttpUrlConnection 默认 follow redirect 吗。

会

2024-03-29 12:29 UTC, Bluemangoo commented
先用z0的了。

2024-03-30 04:22 UTC, s-yh-china approved these changes

2024-03-30 04:23 UTC, s-yh-china commented
没签名(指

2024-03-30 04:26 UTC, Bluemangoo commented
codespace没有gpg。

回家给你签顺便查查有没有漏的，codespace的搜索有点问题。

要不把repo的ssl修了我一起改了吧。

2024-03-30 08:26 UTC, merged