Friendly Bytebuf API
LeavesMC/Leaves pull request #205
Opened 2024-04-13 05:52 UTC by Lumine1909

A possibility of https://github.com/LeavesMC/Leaves/issues/194 (only partially completed)

Example plugin: https://github.com/Lumine1909/BytebufAPIExample/tree/master

TODO: More writable item
for details, see "top.leavesmc.leaves.packet.bytebuf.WrappedBytebuf" and "net.minecraft.network.FriendlyByteBuf"

2024-04-15 08:43 UTC, s-yh-china requested changes
我们能否绕过包装的创建，而直接允许new
我认为这可以使使用体验成倍的增加

2024-04-15 08:43 UTC, s-yh-china commented on patches/api/0011-Bytebuf-API.patch
> ++    public static @NotNull Bytebuf newByteBuf() {
为什么要单独在这里划出来一个方法呢，直接new是不是会更好一点

2024-04-15 08:43 UTC, s-yh-china commented on patches/server/0137-Bytebuf-API-Impl.patch
> +-import org.bukkit.plugin.java.JavaPluginLoader;
遵守原则，不要更改原有依赖

2024-04-15 17:54 UTC, Lumine1909 commented on patches/server/0137-Bytebuf-API-Impl.patch
> +-import org.bukkit.plugin.java.JavaPluginLoader;
Maybe it was done by Idea : (
There is no usage for this import.

2024-04-15 17:58 UTC, Lumine1909 commented
> 我们能否绕过包装的创建，而直接允许new 我认为这可以使使用体验成倍的增加

Like this new version?
The experience doesn’t seem to have changed much (see example), but the implementation becomes stupid.
This implementation is imitate from ItemStack, CraftItemStack and nmsItemStack.

2024-04-17 04:51 UTC, Lumine1909 commented on patches/api/0011-Bytebuf-API.patch
> ++    public static @NotNull Bytebuf newByteBuf() {
See new version qwq

2024-04-17 12:45 UTC, s-yh-china commented
我不是很拿得准 @MC-XiaoHei @Bluemangoo

2024-04-18 02:42 UTC, MC-XiaoHei commented on patches/api/0011-Bytebuf-API.patch
或许应当使用行后注释，避免产生过多无用行

2024-04-18 02:43 UTC, MC-XiaoHei requested changes
或许应当使用行后注释，避免产生过多无用行

2024-04-18 03:49 UTC, Lumine1909 commented on patches/api/0011-Bytebuf-API.patch
API中一共有四个注释，其中两个是包括在nms中但不使用的packet
另外两个都很重要，是实现的相关内容，行后注释可能会被之后的修改者忽略导致问题

不过这个问题我会注意的qwq

2024-04-19 03:15 UTC, s-yh-china reviewed
在这个模式下，我怀疑性能可能出现一些问题

2024-04-19 13:12 UTC, Lumine1909 commented
> 在这个模式下，我怀疑性能可能出现一些问题 要不还是改回去(被打

我倾向于改回去 不知道小黑他们什么意见（

2024-04-19 13:16 UTC, MC-XiaoHei commented
> 在这个模式下，我怀疑性能可能出现一些问题 要不还是改回去(被打

改啥？我觉得性能优先吧，

2024-04-19 13:18 UTC, Bluemangoo approved these changes

2024-04-19 13:18 UTC, Bluemangoo commented on patches/server/0137-Bytebuf-API-Impl.patch
> +-import org.bukkit.plugin.SimplePluginManager;
以后注意一下不要动到这种import顺序吧（

2024-04-21 05:45 UTC, closed without merging