Bytebuf API
LeavesMC/Leaves pull request #206
Opened 2024-04-21 06:01 UTC by Lumine1909

怎么莫名其妙就close了（悲
这个版本是最初的 应该符合之前的讨论了qwq

2024-04-21 06:17 UTC, Bluemangoo commented
不是你自己点的close吗。。你看看那个还能reopen其实。

2024-04-21 06:18 UTC, Bluemangoo commented
另外，你下次贡献的时候开个新分支，不然合并之后你这个分支就废了。

2024-04-21 10:15 UTC, Lumine1909 commented
> 不是你自己点的close吗。。你看看那个还能reopen其实。

不是 莫名其妙就close了

2024-04-21 10:16 UTC, Lumine1909 commented
> 另外，你下次贡献的时候开个新分支，不然合并之后你这个分支就废了。

感谢提醒qwq
如果没有你的提醒没准真要寄（

2024-04-22 07:59 UTC, s-yh-china requested changes
没有什么问题了
还有一点要改，请把类放置在org.leavesmc.leaves下，我们即将更换包名

2024-04-22 07:59 UTC, s-yh-china commented on patches/server/0137-Bytebuf-API-Impl.patch
> ++import org.jetbrains.annotations.NotNull;
请不要增加额外的依赖

2024-04-22 07:59 UTC, s-yh-china commented on patches/server/0137-Bytebuf-API-Impl.patch
> ++import top.leavesmc.leaves.packet.bytebuf.Bytebuf;
这里我认为是没有必要的
下面可以直接使用top.leavesmc.leaves.packet.bytebuf.Bytebuf

2024-04-22 07:59 UTC, s-yh-china commented on patches/server/0137-Bytebuf-API-Impl.patch
> ++import top.leavesmc.leaves.packet.bytebuf.Bytebuf;
一样的问题，如非必要，勿添依赖

2024-04-22 15:44 UTC, Lumine1909 commented
现在nms obc中没有这个api的显式import了
所有去掉的import都是不需要的 可能upstream没处理

2024-04-22 15:58 UTC, s-yh-china requested changes
不要开idea的自动优化import.jpg

2024-04-22 15:58 UTC, s-yh-china commented on patches/server/0137-Bytebuf-API-Impl.patch
> +-import org.bukkit.plugin.java.JavaPluginLoader;
(?

2024-04-22 15:58 UTC, s-yh-china commented on patches/server/0137-Bytebuf-API-Impl.patch
> +-import org.bukkit.craftbukkit.profile.CraftPlayerProfile;
emmmm?

2024-04-23 00:13 UTC, s-yh-china approved these changes

2024-04-23 04:10 UTC, merged

2024-04-23 04:10 UTC, s-yh-china commented
thanks!