修改包名为 org.leavesmc.leaves.xxx, 添加两个bot事件
LeavesMC/Leaves pull request #210
Opened 2024-05-05 04:11 UTC by Lumine1909

BotCreateByPlayerEvent
BotRemoveEvent
@MC-XiaoHei (doge

idea的refactor默认会删掉import（悲
https://intellij-support.jetbrains.com/hc/en-us/community/posts/17685814752530-Why-does-Refactor-suddenly-remove-unused-imports

2024-05-05 04:32 UTC, MC-XiaoHei commented
或许v姐准备1206改包名

2024-05-05 06:28 UTC, Bluemangoo commented
你先别改包名。

2024-05-05 23:11 UTC, Lumine1909 commented
删掉了包名更改，添加了一些实现上的变动（

2024-05-05 23:29 UTC, Bluemangoo commented on patches/api/0012-CreateByPlayer-and-Remove-event.patch
> ++    private final boolean isAsync;
我没有看明白为什么要存这个。

2024-05-05 23:33 UTC, Lumine1909 commented on patches/api/0012-CreateByPlayer-and-Remove-event.patch
> ++    private final boolean isAsync;
防止有人异步操作bukkitapi
BotCreateState有同步和异步两个创建方法 /bot命令是异步创建
监听命令产生的创建事件并使用bkapi可能导致某些问题

有了这个就可以在监听器判断异步，避免上述问题了

2024-05-05 23:43 UTC, s-yh-china requested changes
不应该单独作为一个patch，应该合并回`0010-Fakeplayer-support.patch`

2024-05-06 08:15 UTC, MC-XiaoHei commented
> 或许在BotCreateEvent中添加Source Enum类去标明创建来源会更具有可拓展性 例如分为API，Player，Console等

而不是单独来一个CreateByPlayerEvent

2024-05-06 09:07 UTC, Bluemangoo commented on patches/api/0012-CreateByPlayer-and-Remove-event.patch
> ++    private final boolean isAsync;
举个例子。？

2024-05-06 09:30 UTC, MC-XiaoHei commented on patches/api/0012-CreateByPlayer-and-Remove-event.patch
> ++    private final boolean isAsync;
> 防止有人异步操作bukkitapi BotCreateState有同步和异步两个创建方法 /bot命令是异步创建 监听命令产生的创建事件并使用bkapi可能导致某些问题
> 
> 有了这个就可以在监听器判断异步，避免上述问题了

这种应该分成两个事件（吧

2024-05-06 11:26 UTC, Bluemangoo commented on patches/api/0012-CreateByPlayer-and-Remove-event.patch
> ++    private final boolean isAsync;
我没想明白什么情况下会出问题。

当然我觉得最优雅的解法是.then()传入lambda然后创建后调用（写js写的）。

而且应该是创建时而不是发送命令时发事件吧，真的有区别吗。

2024-05-06 13:04 UTC, MC-XiaoHei commented on patches/api/0012-CreateByPlayer-and-Remove-event.patch
> ++    private final boolean isAsync;
命令时候发这个，创建即加入，发join

2024-05-06 13:34 UTC, Bluemangoo commented on patches/api/0012-CreateByPlayer-and-Remove-event.patch
> ++    private final boolean isAsync;
那既然有join事件，我觉得需要的用join就好了。你就算知道是async的也做不了操作对吧。

2024-05-06 13:45 UTC, Lumine1909 commented
> > 或许在BotCreateEvent中添加Source Enum类去标明创建来源会更具有可拓展性 例如分为API，Player，Console等
> 
> 而不是单独来一个CreateByPlayerEvent
收到，确实是更好的想法

2024-05-06 13:49 UTC, Lumine1909 commented on patches/api/0012-CreateByPlayer-and-Remove-event.patch
> ++    private final boolean isAsync;
> 那既然有join事件，我觉得需要的用join就好了。你就算知道是async的也做不了操作对吧。

建议去翻之前???的聊天记录，在没有api提供creator时获取creator是很折磨的（
另外join是属于bot的，应该仅限于bot本身（就像现在的实现一样），所以不应在这个事件中提供creator

2024-05-06 14:07 UTC, Lumine1909 commented on patches/api/0012-CreateByPlayer-and-Remove-event.patch
> ++    private final boolean isAsync;
> > 防止有人异步操作bukkitapi BotCreateState有同步和异步两个创建方法 /bot命令是异步创建 监听命令产生的创建事件并使用bkapi可能导致某些问题
> > 有了这个就可以在监听器判断异步，避免上述问题了
> 
> 这种应该分成两个事件（吧

那就抽象了，想想看，一个插件想要监听创建事件并记录下创建者，然后不得不监听了两个事件并做相同的事

2024-05-06 23:27 UTC, Bluemangoo commented on patches/api/0012-CreateByPlayer-and-Remove-event.patch
> ++    private final boolean isAsync;
> 建议去翻之前???的聊天记录

给我截一下。

2024-05-07 01:27 UTC, Bluemangoo commented on patches/api/0012-CreateByPlayer-and-Remove-event.patch
> ++    private final boolean isAsync;
要不你给我描述下什么场景需要判断是否async做出不同行为。能不能全部按async算。

2024-05-07 12:08 UTC, Lumine1909 commented on patches/api/0012-CreateByPlayer-and-Remove-event.patch
> ++    private final boolean isAsync;
> > 建议去翻之前???的聊天记录
> 
> 给我截一下。

![image](https://github.com/LeavesMC/Leaves/assets/133463833/761286f0-ff3e-4e5a-84fc-87454390408b)

![image](https://github.com/LeavesMC/Leaves/assets/133463833/5cdb77bb-fd50-42c5-b484-e497a8d35d8b)

![image](https://github.com/LeavesMC/Leaves/assets/133463833/9b2e9cb9-3fb3-443c-9340-43bb9dd12ae4)

![image](https://github.com/LeavesMC/Leaves/assets/133463833/ad504529-5453-4f75-a1b7-5fca9760c0b5)

2024-05-07 12:29 UTC, Bluemangoo commented on patches/api/0012-CreateByPlayer-and-Remove-event.patch
> ++    private final boolean isAsync;
那么是否async的处理的区别是什么。

2024-05-07 12:47 UTC, Lumine1909 commented on patches/api/0012-CreateByPlayer-and-Remove-event.patch
> ++    private final boolean isAsync;
> 那么是否async的处理的区别是什么。

像我说的，一旦有精细时序的需要，BkRunnable可能会有问题
你可以去看一下bkapi(尤其是paper)，包含异步操作的内容都做了异步事件处理

2024-05-08 09:15 UTC, MC-XiaoHei commented
> > > 或许在BotCreateEvent中添加Source Enum类去标明创建来源会更具有可拓展性 例如分为API，Player，Console等
> > 
> > 
> > 而不是单独来一个CreateByPlayerEvent
> > 收到，确实是更好的想法
> > (edit) 我又想了一下，如果这样的话又变的麻烦了，监听玩家创建需要先判断是否来自玩家再获取，否则还有可能产生npe或者cce
> > 看v姐怎么想吧（

我认为这样是正确的，或许可以
```
event.getIfSource<Player>(Source.Player)
```

2024-05-23 07:11 UTC, s-yh-china commented
~~为什么不直接用已有的ConsoleSender和Player来区分呢~~

2024-06-30 14:06 UTC, MC-XiaoHei commented
> ~~为什么不直接用已有的ConsoleSender和Player来区分呢~~

因为不一定是sender创建的 可能是api

2024-06-30 14:16 UTC, Lumine1909 commented
conflict了 等1.21release我再开始搞吧（
外群来的不要急qwq 现在可以用小黑的方法 监听CommandPreProcess事件然后处理即可

2024-07-01 11:41 UTC, Lumine1909 commented
新的版本加了reason和xxer两个字段现在可以直接用类似bukkit command的形式判断了

```java
    private final Map<String, UUID> botOwnerMap = new HashMap<>();
    @EventHandler
    public void onBotCreate(BotCreateEvent e) {
        if (e.getCreator().isPresent() && e.getCreator().get() instanceof Player player) {
            botOwnerMap.put(e.getBot(), player.getUniqueId());
        }
    }
    @EventHandler
    public void onBotRemove(BotRemoveEvent e) {
        if (e.getRemover().isPresent() && e.getRemover().get() instanceof Player player) {
            if (!botOwnerMap.get(e.getBot().getName()).equals(player.getUniqueId())) {
                player.sendMessage(ChatColor.RED + "You can't remove it because it is not your bot!");
            }
        }
    }

````

2024-07-01 14:25 UTC, s-yh-china requested changes
唯一的问题是，自己内部类就没必要写完整包名调用了，直接import就好了

2024-07-01 15:34 UTC, s-yh-china approved these changes

2024-07-01 15:43 UTC, merged