fix and rewrite bytebuf api
LeavesMC/Leaves pull request #218
Opened 2024-05-22 03:50 UTC by Lumine1909

重写了api，适配 1.20.6
支持更多数据包，添加了数据包监听功能
所有新内容已完成本地测试
食用方法: https://github.com/Lumine1909/BytebufAPIExample

2024-05-22 12:46 UTC, s-yh-china requested changes
可能需要对一些文件进行更多格式化

2024-05-23 03:12 UTC, s-yh-china requested changes
首先，格式化，格式化，格式化
然后我不明白，为什么要独立出一个Handler，而不是直接使用原有的事件系统?

2024-05-23 04:53 UTC, Lumine1909 commented
现在格式应该没问题了（吧）

2024-05-23 23:39 UTC, Bluemangoo commented
我觉得除了新开一个handler以外都还好。

改成类似wrapper？

2024-05-24 03:25 UTC, Lumine1909 commented
感谢反射和泛型
感谢反射和泛型
感谢反射和泛型

添加了chat component的支持，具体见 https://github.com/Lumine1909/BytebufAPIExample

2024-05-24 03:25 UTC, Lumine1909 commented
> 我觉得除了新开一个handler以外都还好。
> 
> 改成类似wrapper？

新开是因为bukkit的event实现可能有性能问题（详见群）

2024-05-24 06:21 UTC, Bluemangoo commented
>（详见群）

我现在够不到QQ群啊（大叫），discord and github only.

2024-05-24 06:23 UTC, Bluemangoo commented on patches/api/0011-Bytebuf-API.patch
> ++    //ClientboundBundleDelimiter,
这是为什么。

2024-05-24 16:31 UTC, Lumine1909 commented on patches/api/0011-Bytebuf-API.patch
> ++    //ClientboundBundleDelimiter,
这两个是用来同步实体生成和实体数据的包 没有StreamCodec

2024-05-24 16:32 UTC, Lumine1909 commented
> > （详见群）
> 
> 我现在够不到QQ群啊（大叫），discord and github only.

bkapi的 callEvent用到了反射，而packet是一个极其频繁的事件 可能导致之后

2024-05-24 23:29 UTC, Bluemangoo approved these changes

2024-05-25 08:55 UTC, merged