Two mc-old features
LeavesMC/Leaves pull request #239
Opened 2024-06-26 11:42 UTC by Lumine1909

minecraft-old allowGrindstoneOverstacking
minecraft-old [MC-67](https://bugs.mojang.com/browse/MC-67)

第一个可能还有未知问题 因为我没用过这个功能 我只测了诅咒附魔书
![image](https://github.com/LeavesMC/Leaves/assets/133463833/d319f28b-e076-4159-abeb-7b009465b0eb)
![image](https://github.com/LeavesMC/Leaves/assets/133463833/c893302c-6342-4dda-a148-579e0e2e9621)

2024-06-26 14:09 UTC, s-yh-china commented
哪来的这么多commit
全是问题，我直接合到dev后改了?

2024-06-26 14:24 UTC, s-yh-china requested changes
LeavesConfig修改应该合并到之前的patch

并且不应该是fix类别，应该是{"modify", "minecraft-old"}

~~commit名是不是有点太奇怪了，要不改改~~

2024-06-26 14:50 UTC, s-yh-china approved these changes

2024-06-26 14:57 UTC, merged

2024-06-27 03:34 UTC, Bluemangoo commented
> commit名是不是有点太奇怪了，要不改改

你不是 squash merge 的吗。