Fix and modify Botapi
LeavesMC/Leaves pull request #245
Opened 2024-07-03 08:27 UTC by Lumine1909

所有的更改:

1. 删除了CreateEvent构造方法中的async，因为这个事件只有可能被同步调用
2. 修改了BotManager#createBot中的方法，现在可以在skin String arr或 skin name中任选其一传入，并都提供了bot consumer，使用skin arr时可以直接获取Bot实例
3. 合并了ServerBot中的createSync和createAsync方法，这两个方法的区别只在于是否从mojang api获取皮肤。之前的方案容易产生歧义且难以使用

2024-07-03 08:28 UTC, Lumine1909 commented
有没有办法把这些commit squash一下
看着好难受（

2024-07-03 08:34 UTC, Bluemangoo commented
你下次更新上游用 `git rebase upstream/dev/1.21` 就好了。

已经有的你可以 `rebase -i` 。

2024-07-03 09:25 UTC, s-yh-china requested changes
api需要保持向下兼容，不能直接删除和修改原有的方法.

2024-07-03 11:15 UTC, s-yh-china approved these changes

2024-07-03 12:13 UTC, merged

2024-07-04 00:39 UTC, xiao-k233 commented
历史包袱就是这么来的（