Update bot API, fix #317
LeavesMC/Leaves pull request #318
Opened 2024-08-20 07:05 UTC by Lumine1909

懒得写description了 都是群里+issue说过的东西qwq

2024-08-22 05:57 UTC, Lumine1909 commented
新的更改:
1. 添加了consume, consume_offhand，移除了use的食用功能
2. 更新了API
3. 修复了假人加入/退出消息的颜色问题

2024-08-22 06:02 UTC, s-yh-china requested changes

2024-08-22 06:02 UTC, s-yh-china commented on patches/server/0010-Fakeplayer-support.patch
> ++        Bukkit.getScheduler().runTaskTimer(CraftScheduler.MINECRAFT,  task -> {
同时吃n个东西，不对不对

2024-08-22 16:30 UTC, s-yh-china requested changes
consume部分先删掉吧，我明天再改一下统一加

2024-08-24 03:05 UTC, s-yh-china approved these changes

2024-08-24 03:16 UTC, merged

2024-08-26 08:02 UTC, sunshinezxq commented
55构建我似乎没有看到consume这个动作(

2024-08-26 08:14 UTC, Lumine1909 commented
> 55构建我似乎没有看到consume这个动作(

![image](https://github.com/user-attachments/assets/47722962-e403-489b-b80b-793875ddf0c0)