Fix #317, #324, notify #309
LeavesMC/Leaves pull request #325
Opened 2024-08-26 09:12 UTC by Lumine1909

这是一个很离谱的原因 来自于Mojang的抽象代码 也是我今天自己仔细看才找到的
所有的"假人不像真人"的问题都来自于这个

问题解析：
在之前的版本中, ServerBot#tick的调用链如下:
->ServerBot#tick
    ->ServerPlayer#tick
    ->ServerBot#doTick

注意: ServerPlayer#tick 不包括 super.tick，也就是 Player#tick 不是在这里调用的
Player#tick 来自于 ServerPlayer#tick ，也就是 ServerGamePacketListenerImpl#tick 产生的，而假人根本不会调用这个方法
而 doTick 没有调用 super 的内容，也不会调用到 Player#tick
这就导致了所有玩家相关的内容都没有被调用，自然也不像真人

修复后的调用链:
->ServerBot#tick
    ->ServerPlayer#tick
    ->ServerBot#doTick
        ->ServerPlayer#doTick
            ->Player#tick

已测试的食用和睡觉都正常工作，区块加载需要进一步测试

2024-08-26 10:07 UTC, s-yh-china requested changes

2024-08-26 10:07 UTC, s-yh-china commented on patches/server/0010-Fakeplayer-support.patch
> -+        baseTick();
刻意为之，部分tick中的内容是要被忽略的

2024-08-26 10:07 UTC, s-yh-china commented on patches/server/0010-Fakeplayer-support.patch
> -+        baseTick();
要修复的正确方案应该是把需要的逻辑移动到baseTick

2024-08-26 10:38 UTC, Lumine1909 commented on patches/server/0010-Fakeplayer-support.patch
> -+        baseTick();
如果放到baseTick相当于把Player, LivingEntity的tick全部重写一遍，有点极端了（

2024-08-27 03:53 UTC, Bluemangoo commented on patches/server/0010-Fakeplayer-support.patch
> -+        baseTick();
要么你更极端一点为假人写一个它自己的tick方法。

2024-08-30 04:55 UTC, s-yh-china commented
我决定更极端一点，直接重写假人的tick
先关了

2024-08-30 04:55 UTC, closed without merging