enhance bot api, fix somethings
LeavesMC/Leaves pull request #341
Opened 2024-09-16 09:02 UTC by MC-XiaoHei

我这边没条件测试（x）
按理说没啥问题 编译也过了

2024-09-16 09:36 UTC, s-yh-china requested changes

2024-09-16 09:36 UTC, s-yh-china commented on patches/api/0003-Add-fakeplayer-api.patch
> -+
?删了删了

2024-09-16 09:36 UTC, s-yh-china commented on patches/api/0009-Replay-Mod-API.patch
> --
同上

2024-09-16 09:36 UTC, s-yh-china commented on patches/server/0010-Fakeplayer-support.patch
> ++                    bot.getBotActions().remove(i);
为什么要先get 反正stop不能cancel

2024-09-16 09:36 UTC, s-yh-china commented on patches/server/0010-Fakeplayer-support.patch
> ++        if (!botList.removeBot(bot, BotRemoveEvent.RemoveReason.COMMAND, sender, true)) return;
展开.

2024-09-18 07:13 UTC, MC-XiaoHei commented
修了一下 把stop的cancel做了

2024-09-18 13:05 UTC, s-yh-china approved these changes
虽然很想吐槽你这个换行，但是没啥问题

2024-09-18 13:05 UTC, merged