Revert raid changes
LeavesMC/Leaves pull request #361
Opened 2024-10-23 15:48 UTC by huanli233

Revert raid changes
implements [#299](https://github.com/LeavesMC/Leaves/issues/299)

2024-10-23 16:00 UTC, s-yh-china requested changes
只需要把import修改一下就可以了，同时您可能需要对commit进行签名
很感谢您对leaves做出的贡献

2024-10-23 16:02 UTC, s-yh-china commented on build-data/dev-imports.txt
可以直接回退，这里的内容仅在第一次导入时使用

2024-10-23 16:53 UTC, s-yh-china approved these changes

2024-10-24 00:20 UTC, Bluemangoo approved these changes

2024-10-24 02:00 UTC, merged

2024-10-24 02:00 UTC, s-yh-china commented
thanks!