fix Stackable ShulkerBoxes (#356)
LeavesMC/Leaves pull request #374
Opened 2024-11-15 17:22 UTC by MC-XiaoHei

2024-11-15 17:27 UTC, s-yh-china requested changes
依赖看看要不要改下吧 不改直接合了应该也行

2024-11-15 17:27 UTC, s-yh-china commented on patches/server/0040-Stackable-ShulkerBoxes.patch
> ++            org.bukkit.inventory.ItemStack bkStack = org.bukkit.craftbukkit.inventory.CraftItemStack.asBukkitCopy(itemStack);
自己写的类随便import

2024-11-15 17:29 UTC, MC-XiaoHei commented on patches/server/0040-Stackable-ShulkerBoxes.patch
> ++            org.bukkit.inventory.ItemStack bkStack = org.bukkit.craftbukkit.inventory.CraftItemStack.asBukkitCopy(itemStack);
我关电脑了（
itemstack是不能的 java没有import as
craft我懒了（

2024-11-15 17:29 UTC, MC-XiaoHei commented on patches/server/0040-Stackable-ShulkerBoxes.patch
> ++            org.bukkit.inventory.ItemStack bkStack = org.bukkit.craftbukkit.inventory.CraftItemStack.asBukkitCopy(itemStack);
你要是也懒直接合吧

2024-11-16 00:14 UTC, MC-XiaoHei commented
这个pr甚至解决了无mod背包内堆叠盒子的功能
神奇

2024-11-16 00:15 UTC, merged